export const adjectives = [
    "Funny",
    "Silly",
    "Quirky",
    "Zany",
    "Wacky",
    "Goofy",
    "Hilarious",
    "Amusing",
    "Witty",
    "Clever",
    "Playful",
    "Jolly",
    "Merry",
    "Joyful",
    "Cheerful",
    "Whimsical",
  ];
  
 export const nouns = [
    "Panda",
    "Penguin",
    "Platypus",
    "Narwhal",
    "Unicorn",
    "Dragon",
    "Phoenix",
    "Yeti",
    "Sasquatch",
    "Mermaid",
    "Wizard",
    "Ninja",
    "Pirate",
    "Astronaut",
    "Dinosaur",
    "Robot",
  ];